apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-aws-foundation
  annotations:
    meta.crossplane.io/maintainer: Patrick Lee Scott
    meta.crossplane.io/source: github.com/hops-ops/configuration-aws-foundation
    meta.crossplane.io/description: Unified AWS foundation composing Organization, IdentityCenter, and IPAM XRDs.
spec:
  dependsOn:
  - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: ">=v0.6.0"
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-kubernetes
    version: ">=v1.2.0"
  - configuration: ghcr.io/hops-ops/configuration-aws-organization
    version: ">=v0.14.0"
  - configuration: ghcr.io/hops-ops/configuration-aws-identity-center
    version: ">=v0.5.0"
  - configuration: ghcr.io/hops-ops/configuration-aws-ipam
    version: ">=v0.14.0"
  - configuration: ghcr.io/hops-ops/configuration-aws-network
    version: ">=v0.2.0"
