name: on-pr

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    paths:
      - '.github/workflows/on-pr.yaml'
      - '.gitops/**'
      - 'apis/**'
      - 'examples/**'
      - 'tests/**'
      - 'functions/**'
      - 'upbound.yaml'

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v2.5.0
    with:
      examples: |
        [
          { "example": "examples/foundations/individual.yaml" },
          { "example": "examples/foundations/enterprise.yaml" },
          { "example": "examples/foundations/enterprise.yaml", "observed_resources": "examples/observed-resources/enterprise/steps/1" },
          { "example": "examples/foundations/import-existing.yaml" },
          { "example": "examples/foundations/minimal.yaml" }
        ]
      api_path: apis/foundations
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v2.5.0

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v2.5.0
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      aws: true
      timeout-minutes: 33
      debug-example-path: examples/foundations/minimal.yaml
      debug-resource-types: |
        [
          "organizations.aws.hops.ops.com.ai",
          "identitycenters.aws.hops.ops.com.ai",
          "ipams.aws.hops.ops.com.ai",
          "accounts.aws.hops.ops.com.ai"
        ]

  publish:
    needs:
      - validate
      - test
    uses: unbounded-tech/workflows-crossplane/.github/workflows/publish.yaml@v2.5.0
    secrets: inherit
    with:
      tag: pr-${{ github.event.pull_request.number }}-${{ github.sha }}
