name: on-push-main
on:
  push:
    branches:
    - main
    paths:
      - '.github/workflows/on-push-main.yaml'
      - '.github/workflows/on-version-tagged.yaml'
      - '.gitops/**'
      - 'apis/**'
      - 'examples/**'
      - 'functions/**'
      - 'tests/**'
      - 'upbound.yaml'

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:

  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v2.7.0
    with:
      examples: |
        [
          { "example": "examples/foundations/minimal.yaml" },
          { "example": "examples/foundations/individual.yaml" },
          { "example": "examples/foundations/individual.yaml", "observed_resources": "examples/test/mocks/observed-resources/individual/steps/1" },
          { "example": "examples/foundations/enterprise.yaml" },
          { "example": "examples/foundations/enterprise.yaml", "observed_resources": "examples/test/mocks/observed-resources/enterprise/steps/1" },
          { "example": "examples/foundations/import-existing.yaml" },
          { "example": "examples/foundations/with-networks.yaml" },
          { "example": "examples/foundations/with-ram-shares.yaml" }
        ]
      api_path: apis/foundations
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v2.7.0

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v2.7.0
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      aws: true
      aws-use-oidc: true
      aws-account-id: "034489662075"
      aws-region: us-east-2
      timeout-minutes: 33
      debug-resource-types: |
        [
          "organizations.aws.hops.ops.com.ai",
          "identitycenters.aws.hops.ops.com.ai",
          "ipams.aws.hops.ops.com.ai",
          "accounts.aws.hops.ops.com.ai"
        ]

  version-and-tag:
    name: Version and Tag
    needs:
      - validate
      - test
      - e2e
    uses: unbounded-tech/workflow-vnext-tag/.github/workflows/workflow.yaml@v1.20.2
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    with:
      useDeployKey: true
      yqPatches: |
        patches:
          - filePath: .gitops/deploy/values.yaml
            selector: .version
            valuePrefix: "v"
          - filePath: .gitops/deploy/Chart.yaml
            selector: .version
            valuePrefix: ""
